version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  trigger-docker-build:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trigger docker build
          command: .circleci/trigger-docker-build.sh

workflows:
  version: 2
  build-any-branch:
    jobs:
      - maven/test:
          name: build-and-test
          settings_file: .circleci/settings.xml
          command: "-Psecurity-check -B -Dsonar.projectKey=ch.guengel.apod:apod-crawler -Dsonar.qualitygate.wait=true clean install sonar:sonar"
          context:
            - sonar
            - maven-repository-read
      - maven/test:
          name: deploy-maven-artifact
          settings_file: .circleci/settings.xml
          command: "-B -DskipTests deploy"
          requires:
            - build-and-test
          context:
            - maven-repository-write
      - trigger-docker-build:
          filters:
            branches:
              only:
                - master
          context:
            - circle-ci
          requires:
            - deploy-maven-artifact

  daily-dependency-check:
    triggers:
      - schedule:
          cron: "21 4 * * *"
          filters:
            branches:
              only:
                - master
                - develop

    jobs:
      - maven/test:
          name: check-dependencies
          settings_file: .circleci/settings.xml
          command: "-Psecurity-check -B depdendency-check:check"
          context:
            - maven-repository-read
